//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_88888
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплаты.
    /// </summary>
    // *** Start programmer edit section *** (ТипОплаты CustomAttributes)

    // *** End programmer edit section *** (ТипОплаты CustomAttributes)
    public enum ТипОплаты
    {
        
        // *** Start programmer edit section *** (ТипОплаты.1 CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (ТипОплаты.2 CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (ТипОплаты.3 CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.3 CustomAttributes)
        3,
        
        // *** Start programmer edit section *** (ТипОплаты.4 CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.4 CustomAttributes)
        4,
    }
}
